require: rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

RSpec/ExampleLength:
  Max: 10
